# Local development database container for Course Grade Tracker
# Not used in production, only for local development

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: course_grade_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      start_interval: 5s
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
