name: course-grade-tracker

services:
  frontend:
    build:
      context: ../frontend
      args:
        - VITE_API_BASE_URL=http://localhost:3000/api
    ports:
      - 5000:80
    networks:
      - public_network
    restart: unless-stopped

  backend:
    build: ../backend
    ports:
      - 3000:3000
    env_file:
      - ./.env.shared
      - ./.env.backend
    environment:
      - PORT=3000
      - DATABASE_URI=mongodb://${MONGODB_ROOT_USERNAME:-admin}:${MONGODB_ROOT_PASSWORD:-password}@db:27017/${MONGODB_INITDB_DATABASE:-course_grade_tracker}
      - DATABASE_NAME=${MONGODB_INITDB_DATABASE:-course_grade_tracker}
    networks:
      - public_network
      - private_network
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: mongo:8
    env_file:
      - ./.env.shared
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME:-admin}
      - MONGO_INITDB_DATABASE=${MONGODB_INITDB_DATABASE:-course_grade_tracker}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD:-password}
    volumes:
      - db_data:/data/db
    networks:
      - private_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      start_period: 5s
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  db_data:

networks:
  public_network:
    driver: bridge
  private_network:
    internal: true
