name: Check & Deploy Frontend

on:
  push:
    branches:
      - master
      - dev
    paths:
      - "frontend/**"

jobs:
  check-frontend:
    runs-on: ubuntu-latest
    name: Check Frontend
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node modules caching 
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Check code formatting
        run: npm run format:check

      - name: Check code linting
        run: npm run lint:check

      - name: Build app
        run: npm run build

  deploy-frontend:
    needs: check-frontend
    runs-on: ubuntu-latest
    name: Deploy Frontend
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set tag
        id: tag
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          TAG="staging-latest"
          if [ "$BRANCH_NAME" = "master" ]; then
            TAG="production-latest"
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build docker image
        run: docker build --build-arg VITE_BASE_API_URL=https://api.example.com \
            -t ${{ secrets.DOCKERHUB_ORG }}/course-grade-tracker-frontend:${{ steps.tag.outputs.tag }} .

      - name: Push docker image
        run: docker push ${{ secrets.DOCKERHUB_ORG }}/course-grade-tracker-frontend:${{ steps.tag.outputs.tag }}
