name: Cluster Deployer

on:
  workflow_call:
    secrets:
      DO_API_TOKEN:
        required: true

jobs:
  deploy-cluster:
    runs-on: ubuntu-latest
    name: Deploy to DigitalOcean Kubernetes
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install doctl
        run: |
          curl -LO https://github.com/digitalocean/doctl/releases/download/v1.131.0/doctl-1.131.0-linux-amd64.tar.gz
          tar -xzf doctl-1.131.0-linux-amd64.tar.gz
          sudo mv doctl /usr/local/bin
          rm doctl-1.131.0-linux-amd64.tar.gz

      - name: Authenticate doctl
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DO_API_TOKEN }}
        run: doctl auth init -t $DIGITALOCEAN_ACCESS_TOKEN

      - name: Get kubeconfig
        run: doctl kubernetes cluster kubeconfig save course-grade-tracker-cluster

      - name: Deploy manifests
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.9.1/deploy/static/provider/cloud/deploy.yaml
          kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/secret.yaml
          kubectl apply -f k8s/configmap.yaml
          kubectl apply -f k8s/mongodb/
          kubectl apply -f k8s/backend/
          kubectl apply -f k8s/frontend/
          kubectl apply -f k8s/ingress.yaml

          kubectl rollout restart deployment backend -n course-grade-tracker
          kubectl rollout restart deployment frontend -n course-grade-tracker
