name: Deploy Cluster to DigitalOcean

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "k8s/**"

jobs:
  deploy-cluster:
    uses: ./.github/workflows/cluster-deployer.yaml
    secrets:
      DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}