name: Deploy Cluster to DigitalOcean Kubernetes

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "k8s/**"

jobs:
  deploy-cluster:
    uses: ./.github/workflows/reusable/cluster-deployer.yaml